name: Main CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build-test-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.0.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: test with maven
        run: mvn clean test --file jwa/pom.xml

      - name: Upload code coverage as artifact
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        uses: actions/upload-artifact@v2
        with:
          name: code coverage
          path: jwa/target/site/jacoco

      - name: build project
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        run: mvn clean install --file jwa/pom.xml

      - name: Create netrc file
        id: netrc
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        run: |
          cat > ~/.netrc << EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          EOF
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

      - name: Heroku login
        id: login
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        run: npx heroku login

      - name: Install heroku-deploy plugin
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        run: npx heroku plugins:install heroku-cli-deploy

      - name: deploy WAR file
        if: success() && github.event_name == 'push' && github.ref_name == 'master'
        run: npx heroku deploy:war --war jwa/target/jwa.war --app $HEROKU_APP_NAME
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

      - name: Heroku logout
        if: always() && steps.login.outcome == 'success' && github.event_name == 'push' && github.ref_name == 'master'
        run: npx heroku logout

      - name: Delete netrc file
        if: always() && steps.netrc.outcome == 'success'
        run: rm ~/.netrc

      - name: Create Github issue on failure
        if: failure()
        uses: ManojCSE17/open-issue@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Build failed on ${{github.event_name}} to the ${{ github.ref_name }}"
          assignees: |
            ManojCSE17
            manojitdev
