name: Building Java Project using GitHub CICD
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

jobs:
  build-test-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: test with maven
        run: mvn clean install --file JavaGitHubActions/pom.xml
      - name: build project
        if: ${{ github.event_name == 'push' }}
        run: mvn package --file JavaGitHubActions/pom.xml

      - id: 'auth'
        if: |
          github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - id: 'deploy-to-gcp'
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: 'google-github-actions/deploy-appengine@v0.6.0'
        with:
          deliverables: JavaGitHubActions/src/main/appengine/app.yaml

      - name: 'Set up Cloud SDK'
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: 'google-github-actions/setup-gcloud@v0.5.0'

      - name: 'Using gcloud CLI'
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: 'mvn package appengine:deploy --file JavaGitHubActions/pom.xml -Dapp.deploy.projectId=${{ secrets.GCP_PROJECT }}'

      - id: test-gcp
        if: |
          success() && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: curl "${{ steps.deploy-to-gcp.outputs.url }}"
